#
PROJECT_FONT = 'Courier New'               # 'fixed'
PROJECT_FONT_SMALL = 'Courier New'
PROJECT_FONT_BOLD = 'Courier New'
# FONT_NORMAL = (PROJECT_FONT, 10)
FONT_LARGE = (PROJECT_FONT, 16)
FONT_V_LARGE_BOLD = (PROJECT_FONT, 20, 'bold')
FONT_LARGE_BOLD = (PROJECT_FONT_BOLD, 16, 'bold')
FONT_SUPER_LARGE_BOLD = (PROJECT_FONT, 105, 'bold')
FONT_VERY_LARGE_BOLD = (PROJECT_FONT, 85, 'bold')
FONT_NORMAL = (PROJECT_FONT, 14)
FONT_SMALL = (PROJECT_FONT, 10)
FONT_SMALLEST = (PROJECT_FONT, 8)
FONT_BOLD = (PROJECT_FONT, 14, 'bold')
BLANK_LINE = (PROJECT_FONT, 2)
BUTTON_FONT_LARGE = (PROJECT_FONT, 35)