from Constants import font_info as fi

#
PROJECT_THEME = 'DarkAmber'
# "DarkAmber": {"BACKGROUND": "#2c2825",
#               "TEXT": "#fdcb52",
#               "INPUT": "#705e52",
#               "TEXT_INPUT": "#fdcb52",
#               "SCROLL": "#705e52",
#               "BUTTON": ("#000000", "#fdcb52"),
#               "PROGRESS": DEFAULT_PROGRESS_BAR_COMPUTE, "BORDER": 1,
#               "SLIDER_DEPTH": 0, "PROGRESS_DEPTH": 0, }
MULTILINE_BACKGROUND_COLOR = '#2c2825'
INPUT_BACKGROUND_COLOR = '#705e52'
NUMERIC_KEYPAD_ENTER_BINDING_CODE = '<KP_Enter>'
ENTER_BINDING_CODE = '<Return>'
#
ENTER = '_E'
RELEASE = '_R'
#
USE_DETECTION_LASER = True
#
CAPTURE_FOCUS_DATA_ONLY_FLAG: bool = False
NO_OUTLIER_REMOVAL_FLAG: bool = False
REPEAT_SCAN_N_TIMES = 5
#
DEFAULT_SCREEN_SCALING = 1.4305  # Kristof's screen - will be adjusted automatically to other screens
SCALING = None
GUI_REF_DPI = 72
MM_PER_INCH = 25.4
LOSS_PLOT_FIGURE_SIZE: tuple[int, int] = (11, 5)
ITERATION_LOSS_PLOT_FIGURE_SIZE: tuple[int, int] = (11, 6)
FOCUS_PLOT_FIGURE_SIZE: tuple[int, int] = (13, 10)
#
PROJECT_FONT = fi.PROJECT_FONT
PROJECT_FONT_BOLD = fi.PROJECT_FONT_BOLD
FONT_NORMAL = fi.FONT_NORMAL
FONT_NORMAL_SMALL = fi.PROJECT_FONT_SMALL
FONT_SMALLEST = fi.FONT_SMALLEST
FONT_LARGE = fi.FONT_LARGE
FONT_SMALL = fi.FONT_SMALL
FONT_BOLD = fi.FONT_BOLD
FONT_LARGE_BOLD = fi.FONT_LARGE_BOLD
FONT_V_LARGE_BOLD = fi.FONT_V_LARGE_BOLD
BLANK_LINE = fi.BLANK_LINE
#
# BUTTON CONTROL
BUTTON_FONT_LARGE = fi.BUTTON_FONT_LARGE
FONT_VERY_LARGE_BOLD = fi.FONT_VERY_LARGE_BOLD
MAIN_BUTTON_SIZE = (14, 1)
SMALL_MAIN_BUTTON_SIZE = (10, 1)
MAIN_BUTTON_WIDE_SIZE = (20, 1)
ROI_BUTTON_SIZE = (15, 1)
#
# Generic window operations
NORMAL_WINDOW = '#@'
MINIMIZE_WINDOW = '@#'
# Window keys
MAIN_WINDOW_KEY = '#mwk'
PATH_WINDOW_KEY = '#pwk'
DEMO_WINDOW_KEY = '#dwk'
SLIDE_INFO_WINDOW_KEY = '#swk-'
IMAGE_WINDOW_KEY = '#iwk'
MESSAGE_HANDLER_KEY = '#mhk'
#
# Constants for [globals] dictionary
cCURRENT_CTL_COMM_OWNER = 'CCCO'    # who is supposed to receive updates from controller
#
cTEMPERATURE_DIR_PATH = "./TEMP/"
cTEMPERATURE_UPDATE_STR = '^tu'
#
cRISING_ICON = "./Images/icons8-arrow-up-24.png"
cLOWERING_ICON = "./Images/icons8-arrow-down-24.png"
cLEVEL_ICON = "./Images/icons8-arrow-right-24.png"
#
OK = '-OK-'
CANCEL = '-CANCEL-'
ENABLE_TABS = '!en'
DISABLE_TABS = '@di'
STAGES_MOTION_IN_PROGRESS = '###'
SEND_MEMS_RUN_PROFILE = '##smrp'
UPDATE_MASTER_OFFSET = '##umo'
UPDATE_PATH_GRID_OFFSET = '#pgO'
STAGES_IDLE = 'idle'
CONTROLLER_STOPPED = 'stopped'
#
REPEAT_SCANS = '$RS'
DO_NOT_REPEAT_SCANS = '$dnRS'
#
PROCESS_INTERRUPTED = -2
EVENT_HANDLED = -1
CLOSE_WINDOW = 0
#
DEFAULT_MESSAGE_DURATION = 2500
#  Controller even handler responses
CONTROLLER_EVENT_HANDLED = -1
#
# event handler dictionary keys
EVENT_HANDLER_RESULT = '-res-'
EVENT_CONTROLLER_CREATED_WINDOW = '-Cn_w-'
EVENT_RESULT_PARAMETERS = '-params-'
PARAM_NEW_WINDOW = '-w-'
USER_PARAMS = '-up-'
FILE_PATH = '-fp-'
RETURNING_FOR_EVENT = '-rfe-'

# Communication queue dictionary keys
PROGRESS_WINDOW_TO_UPDATE = '-pwtu-'
STATUS_BAR_TO_UPDATE = '-sbtu-'
REPLY_INFO_FOR_COMMAND = '-rIFc-'
ORIGINAL_SENDER = '-OS-'

# message handler thread dictionary keys
RMG_QUEUE_KEY = '#rmg'
COMM_QUEUE_KEY = '#cmq'

#
# Main window global control buttons
QUIT_BUTTON = '$Q-'
CONNECT_BUTTON = '$C-'
DONE_BUTTON = '-DONE'
START_BUTTON = '$tart'
STOP_BUTTON = '$top'
RESET_BUTTON = '$rst'
RESET_STAGE_BUTTON = '$rstge'
QUIT_CTL_ON_EXIT = '-Qctl$'
SHOW_LOGGING_WINDOW = '-SLW'


# Window widget constants
DOVER_STATUS_BAR = '-sB'
PATH_PLANNER_FRAME = '#ppf'
PATH_PLANNER_LABEL = ' Path planner - Machine View '
#
MOVES_TAB = '$MT-'
MANUAL_MOVES_TAB = '$PMT'
SECTION_MOVES_TAB = '$SMT'
MEMS_SETUP_TAB = '$LST'
LASER_SETUP_TAB = '#OXX'
FOCUS_TEST_TAB = '#ftt'
AUTO_FOCUS_TAB = '#auf'
STAGE_CALIBRATION_TAB = '$scT'
SYSTEM_CONFIG_TAB = '$SCT'
PATH_TAB = '$PT'
TABS_KEY = '$TK$'

#
# Pre-programmed moves tab
Z_SPEED_SLIDER_1 = '-Z1S$'
X_SPEED_SLIDER_1 = '-X1S$'
Y_SPEED_SLIDER_1 = '-Y1S$'
Z_SPEED_SLIDER_2 = '-Z2S$'
X_SPEED_SLIDER_2 = '-X2S$'
Y_SPEED_SLIDER_2 = '-Y2S$'
Z_CB_ALT = '-ZCB'
Z_SPEED_SLIDER_3_ALT = '-Z3S$'
X_CB_ALT = '-XCB'
X_SPEED_SLIDER_3_ALT = '-X3S$'
Y_CB_ALT = '-YCB'
Y_SPEED_SLIDER_3_ALT = '-Y3S$'
EXECUTE_Z_MOVE_1 = '@M-Z-1'
EXECUTE_X_MOVE_1 = '-ExM-'
EXECUTE_Y_MOVE_1 = '-EyM-'
EXECUTE_COMPOUND_MOVE = '-ECM'

# Section Move tab
MASTER_ROW_VALUE = '$mrv'
MASTER_COLUMN_VALUE = '$mcv'
ROW_SLIDER = '$r'
COLUMN_SLIDER = '$c'
EXECUTED_SECTION_MOVES = '#esm'
CLEAR_SECTION_MOVE_LOG = 'clrSML'
EXECUTE_SECTION_MOVE = '$ex'
TOP_LEFT_CORNER_R = '#0'
BOTTOM_RIGHT_CORNER_R = '#1'
SCAN_START_R = '#2'
SCAN_END_R = '#3'
FOCUS_START_R = '#4'
FOCUS_END_R = '#5'
SECTION_POSITIONS = [TOP_LEFT_CORNER_R, BOTTOM_RIGHT_CORNER_R, SCAN_START_R, SCAN_END_R, FOCUS_START_R, FOCUS_END_R]
SCAN_OFFSET_S = '#sos'
SCAN_OFFSET_r0 = '#o0'

POSITION_LABELS: dict = {TOP_LEFT_CORNER_R: "Top-Left-Corner",
                         BOTTOM_RIGHT_CORNER_R: "Bottom-Right-Corner",
                         SCAN_START_R: "Scan-Start",
                         SCAN_END_R: "Scan-End",
                         FOCUS_START_R: "Focus-Start",
                         FOCUS_END_R: "Focus-End"
                         }

# Path window
EXECUTE_PATH_MOVE = 'cPM#'
EXECUTE_CAMERA_PATH_MOVES = '#cpm'
CANCEL_PATH_EXECUTION = '#Cpe'
CLEAR_PATH_LOG = '#clrPL'
SAVE_PATH_LOG = '#svPL'
PATH_TABLE = '-TBL-'
SIM_DELAY_SL = 'sim$'
X_MULTIPLIER_CB = 'xM$'
Y_MULTIPLIER_CB = 'yM$'
Z_MULTIPLIER_CB = 'zM$'
Z_MULTIPLIER_VAL = 'zMV#'
X_MULTIPLIER_VAL = 'xMV#'
Y_MULTIPLIER_VAL = 'xMV#'
CLEAR_PATH_BTN = '-cP#'
SAVE_PATH_BTN = 'savePb'
LOAD_PATH_BTN = 'loadPb'
RESET_SCAN_BTN = 'resetPb'
FILL_PATH_BTN = 'fill'
GEN_JSON_BTN = 'json'
EXTERNAL_JSON_BTN = '=ej'
# SIMULATE_SCAN_PATH1 = 'simSP1'
SIM_TIME_TIME_1 = '@st1'
SIMULATE_SCAN_PATH2 = 'simSP2'
SIM_TIME_TIME_2 = '@st2'
OPERATION_TYPE = '!op'
SECTION_ROW_COL = '!rc'
MASTER_SECTION_ROW_COL = '!mrc'
MASTER_ROW_SCAN_RANGE = '!mrsr'
MASTER_COLUMN_SCAN_RANGE = '!mcsr'
MASTER_SECTION_OFFSET_COLS = '@msco'
MASTER_SECTION_OFFSET_ROWS = '@msro'
Z_SPEED_PATH = 'zSPath'
X_SPEED_PATH = 'xSPath'
Y_SPEED_PATH = 'ySPath'
MO_LOG = 'moL0g'
CLEAR_MO_LOG_BTN = 'clrML'
PATH_STATUS_BAR = 'pathSB'
PATH_LOG = '#pL#'
IGNORE_TIMING_CB = "#it#"
RUN_SECTION_TRACE_CB = '#rst'
MOTION_PROFILE_RADIO_GROUP = '@mpg'
SCAN_TYPE_PROFILE_RADIO_GROUP = '@stg'
NORMAL_SCAN_RB = '#NS'
SCAN_MOVES_ONLY_RB = '#SM'
HIGH_MOTION_PROFILE = '@high'
MEDIUM_MOTION_PROFILE = '@med'
LOW_MOTION_PROFILE = '@low'
MOTION_INSTRUMENT_PROFILE = '@mip'
STANDARD_PROFILE = '@@S'
TEST1_PROFILE = '@@1'
TEST2_PROFILE = '@@2'
TEST3_PROFILE = '@@3'
TEST4_PROFILE = '@@4'
TEST5_PROFILE = '@@5'
TEST6_PROFILE = '@@6'
TEST7_PROFILE = '@@7'
TEST8_PROFILE = '@@8'
#
JOG_ACCEL_SL = '*jas'
JOG_JERK_SL = '*jjs'
SCAN_ACCEL_SL = '*sas'
SCAN_JERK_SL = '*sjs'
FOCUS_ACCEL_SL = '*fas'
FOCUS_JERK_SL = '*fjs'
#
RECONSTRUCTION_NOTIFICATION = "*reCon"

# programmed move
Z_SPEED_PM = 'zsPM'
X_SPEED_PM = 'xsPM'
Y_SPEED_PM = 'ysPM'
Z_POSITION_PM = 'zpPM'
X_POSITION_PM = 'xpPM'
Y_POSITION_PM = 'ypPM'
MOVE_STAGE_X_AP = 'mxPM'
MOVE_STAGE_Y_AP = 'myPM'
MOVE_STAGE_Z_AP = 'mzPM'
MOVE_STAGES_AP = 'msPM'
CLEAR_PROGRAMMED_MOVE_LOG = 'clrPML'
REPORTED_X_POS_PM = '-rxPM'
REPORTED_Y_POS_PM = '-ryPM'
REPORTED_Z_POS_PM = '-rzPM'
INPUT_X_PM = 'ixPM'
INPUT_X_PM_ENTER = INPUT_X_PM + ENTER
INPUT_Y_PM = 'iyPM'
INPUT_Y_PM_ENTER = INPUT_Y_PM + ENTER
INPUT_Z_PM = 'izPM'
INPUT_Z_PM_ENTER = INPUT_Z_PM + ENTER
PM_LOG = 'pmL0g'
#
# laser layout
X_SIGNAL_COMBO = '-ySc'
X_SIGNAL_COMBO_SINE = ' Sine '
X_SIGNAL_COMBO_DC = ' DC '
Y_VOLTAGE_SLIDER = '-xVs-'
LIVE_CONTROL = '-lc-'
QUIT_MEMS_ON_EXIT = '-qme-'
X_AMPLITUDE_SLIDER = '-yAs'
X_FREQUENCY_SLIDER = '-yFs'
SAMPLE_RATE_SLIDER = '-sRs'
SAMPLE_POINTS_GEN = '-sRPG'
SETTINGS_FRAME = '-sF'
ENABLE_MEMS_DRIVER = '-eMd'
ENABLE_DIGITAL_OUT = '-eDo'
V_DIFFERENCE_SLIDER = '-vDs'
CUTOFF_SLIDER = '-cOs'
START_LASER_SCAN_BTN = '-ssB'
RESET_LASER_BTN = '-reLB'
RED_LASER_ON_CB = '-rlo'
START_OXXIUS_LASER_BTN = '-+Ox'
STOP_OXXIUS_LASER_BTN = '--Ox'
DETECTION_POWER_SCAN_SLIDER = '-oxPS'
DETECTION_POWER_FOCUS_SLIDER = '-oxPF'
OXXIUS_SCAN_POWER_SET_BTN = '-oxSS'
OXXIUS_FOCUS_POWER_SET_BTN = '-oxSF'
DETECTION_LASER_ON_BTN = '-la'
DETECTION_LASER_OFF_BTN = '-lao'
DETECTION_AUTO_MORNING_START_CB = '-bAS'
DETECTION_SHUTDOWN_CB = '-sh'
X_AMPLITUDE_FRAME = '-yaF'
X_FREQUENCY_FRAME = '-yfF'
DETECTION_TEMPERATURE_FLD = '-tF'
DETECTION_FREQUENCY_FLD = '-fF'
DETECTION_AMPLITUDE_FLD = '-aF'

# ==============================
TOGGLE_RED_LASER_BTN = '-trl-'
SAMPLE_RATE_FRAME = '-sRF'
SAMPLE_POINTS_FRAME = '-sSMF'
LASER_STATUS_BAR = '-sBL'
LASER_LOG = '-llML'
CLEAR_LASER_LOG_BTN = '-cLL'
SET_MEMS_RUN_PROFILE_BTN = '-sMrP'
RESET_MEMS_PARAMS_BTN = '-rMp'
LOAD_STORED_MEMS_PROFILE = '+lSmP'
#
# Focus testing tab in main window
ROW_SECTION_SLIDER_FT = '*rsft'
COL_SECTION_SLIDER_FT = '*csft'
Z_VELOCITY_SLIDER_FT = '*zv'
Z_POSITION_SLIDER_FT = '*fts'
Z_POSITION_SLIDER_FT_RELEASE = Z_POSITION_SLIDER_FT + RELEASE
X_POSITION_SLIDER_FT = '*fcx'
Y_POSITION_SLIDER_FT = '*fcy'
SECTION_MOTION_RB_FT = '*smr'
ABSOLUTE_POSITION_RB_FT = '*apr'
SECTION_FRAME_FT = '*sf-'
ABSOLUTE_POSITION_FRAME_FT = '*ap-'
COLUMN_RANGE_TXT_FT = '&&1'
ROW_RANGE_TXT_FT = '&&2'
Z_VELOCITY_TXT_FT = '&&3'
X_POSITION_TXT_FT = '&&4'
Y_POSITION_TXT_FT = '&&5'
FOCUS_STEP_GROUP = 10
ONE_MICRON = '0.0001'
FIVE_MICRONS = '0.0005'
TEN_MICRONS = '0.001'
TWENTY_MICRONS = '0.002'
FIFTY_MICRONS = '0.005'
HUNDRED_MICRONS = '0.01'
TWO_HUNDRED_MICRONS = '0.02'
THREE_HUNDRED_MICRONS = '0.03'
FOUR_HUNDRED_MICRONS = '0.04'
FIVE_HUNDRED_MICRONS = '0.05'
THOUSAND_MICRONS = '0.1'
USE_FOCUS_START_RB = '&m0'
USE_SCAN_START_RB = '&m1'
USE_STATIONARY_START_RB = '&m2'
LIVE_Z_ADJUSTMENTS_CB = '#lza'
EXECUTE_X_AXIS_MOVES_BTN = '#exm'
ZERO_SLIDER_BTN = '#zs'
FORCE_Z_VALUE = '#fzv'
FOCUS_TEST_LOG = '%ftl'
FOCUS_TEST_LOG_CLEAR_BTN = '%flcb'
FOCUS_TEST_LOG_SAVE_BTN = '%flsb'
STEP_RADIO_EVENTS = [ONE_MICRON, FIVE_MICRONS, TEN_MICRONS, TWENTY_MICRONS, FIFTY_MICRONS, HUNDRED_MICRONS, TWO_HUNDRED_MICRONS,
                     THREE_HUNDRED_MICRONS, FOUR_HUNDRED_MICRONS, FIVE_HUNDRED_MICRONS, THOUSAND_MICRONS]


# auto focus tab
AUTO_FOCUS_ROW_SLIDER = 'afR#'
AUTO_FOCUS_COL_SLIDER = 'afC#'
START_Z_INPUT = 'afSZ#'
CENTER_Z_INPUT = 'afCZ#'
START_Z_INPUT_RETURN = START_Z_INPUT + ENTER
CENTER_Z_INPUT_RETURN = CENTER_Z_INPUT + ENTER

DEFAULT_START_Z_LBL = '0.000'
Z_PLANE_COUNT_SLIDER = 'afZ#'
AF_RB_GROUP = 25
AF_FIVE_MICRONS_RB = '+0.0005'
AF_TEN_MICRONS_RB = '+0.001'
AF_TWENTY_MICRONS_RB = '+0.002'
AF_FIFTY_MICRONS_RB = '+0.005'
AF_HUNDRED_MICRONS_RB = '+0.01'
AF_FIVE_HUNDRED_MICRONS_RB = '+0.05'

AF_RB_LIST = [AF_FIVE_MICRONS_RB, AF_TEN_MICRONS_RB, AF_TWENTY_MICRONS_RB, AF_FIFTY_MICRONS_RB,
              AF_HUNDRED_MICRONS_RB, AF_FIVE_HUNDRED_MICRONS_RB]
AF_CALCULATE_FOCUS_BTN = 'afCFB#'
AF_SET_Z_BTN = 'afSZ'
AF_SUGGESTED_FOCUS_LBL = '=afSf'
AF_USE_ABSOLUTE_XY_CB = 'afUXY'
AF_PLOT_CANVAS = 'afPC'
AF_RANGE_FRAME_KEY = 'afRF+'
AF_RANGE_TXT_KEY = 'afRX+'


# Stage calibration tab
X_POSITION_SLIDER_CL = '*xCL'
X_POSITION_INPUT = '*xIn'
X_POSITION_INPUT_ENTER = X_POSITION_INPUT + ENTER
Y_POSITION_SLIDER_CL = '*yCL'
Y_POSITION_INPUT = '*yIn'
Y_POSITION_INPUT_ENTER = Y_POSITION_INPUT + ENTER
Z_POSITION_SLIDER_CL = '*zCL'
Z_OFFSET_POSITION_SLIDER_CL = '*zOff'
Z_POSITION_INPUT = '*zIn'
Z_POSITION_INPUT_ENTER = Z_POSITION_INPUT + ENTER
Z_OFFSET_INPUT = '*zOfI'
Z_OFFSET_INPUT_ENTER = Z_OFFSET_INPUT + ENTER
X_POSITION_TXT_CL = '*xClt'
Y_POSITION_TXT_CL = '*yCLt'
Z_POSITION_TXT_CL = '*zCLt'
PATH_SECTION_00_OFFSET_COLS = '*00c'
PATH_SECTION_00_OFFSET_COLS_RELEASE = PATH_SECTION_00_OFFSET_COLS + RELEASE
PATH_SECTION_00_OFFSET_ROWS = '*00r'
PATH_SECTION_00_OFFSET_ROWS_RELEASE = PATH_SECTION_00_OFFSET_ROWS + RELEASE
SC_TEST_LOG = '*lCL'
SC_SET_ANCHOR_LOCATIONS_BTN = '*sal'
SC_LOG_CLEAR_BTN = '*cCL'
SC_LOG_SAVE_BTN = '*sCL'
SC_PATH_GRID_OFFSET_BTN = '*pgo'
SC_SAVE_CALIBRATION_BTN = '*sC+'
SC_LOAD_CALIBRATION_BTN = '*lC+'
#
# System / module settings
BATCH_RECONSTRUCTION_RB = '=brRb'
SINGLE_FILE_RECONTRUCTION_RB = '=sfrRb'
DELETE_CHANNEL_FILES_CB = '=dcfCb'
SCATTERING_ONLY_CB = '=sclCb'
SAVE_FOCUS_DATA_TO_CSV_CB = '=sdfCb'
CAPTURE_FOCUS_DATA_ONLY_CB = '=cfdOCb'
CALC_PLANE_COEFFS_ONLY_CB = '-cpCb'
USE_BOTH_GAGE_CARDS_CB = '=ubgc'
MULTI_THREADED_RECONSTRUCTION_CB = '=mtrCb'
MULTI_THREADED_TRANSFORMATION_CB = '=mtTCb'
DELETE_FOCUS_BIN_FILES_CB = '=dFBCb'
USE_COMPRESSION_CB = '=cfCb'
REPEAT_SCANS_AUTOMATICALLY = '=RS+'
REPEAT_COUNT_SLIDER = '=RCS'
KEEP_SECTION_IMAGE_FILES_CB = '=ke'
OVERRIDE_SHUTTER_CB = '=Os'     # true or false
SHUTTER_POSITION_CB = '=sP'     # true - shutter opened, false - shutter closed
# Oxxius warmup
OXXIUS_WARMUP_CB = '=oW'
# FOCUSING control
FOCUS_RB_GROUP = '-f+'
NO_FOCUS_RB = 'F-'
NORMAL_FOCUS_RB = 'F+'
AUTOFOCUS_RB = 'A+'
AUTOFOCUS_INTERVAL_RB = 'Ai+'
CALCULATED_Z_PLANE_RB = 'cPl'
NO_OUTLIER_REMOVAL_CB = '!nro'
AUTOFOCUS_INTERVAL_SLIDER = 'fi+?'
BIS_FOCUSING_PARAMS_CB = 'bfP'
CMF_USE_ONLY_OVERRIDE_CB = 'CMF'
FOCUS_Z_PLANE_IN = 'FzPi'
FOCUS_Z_PLANE_IN_ENTER = FOCUS_Z_PLANE_IN + ENTER
FOCUSING_FRAME_EVENTS = [NO_FOCUS_RB, NORMAL_FOCUS_RB, AUTOFOCUS_RB,
                         AUTOFOCUS_INTERVAL_RB, FOCUS_Z_PLANE_IN_ENTER,
                         AUTOFOCUS_INTERVAL_SLIDER, CALCULATED_Z_PLANE_RB]
#
TIFF_SIZE_GROUP = 'tSG'
TIFF_16_DATA_SIZE = 't16'
TIFF_8_DATA_SIZE = 't8'
#
QUIT_TRANSFORMER = '=QR'
QUIT_RECONSTRUCTOR_CB = '=qr'
QUIT_CAPTURE_CB = '=cc'
QUIT_SAFEMON_CB = '=sm'
QUIT_STITCHER_CB = '=st'
QUIT_STAINER_CB = '=qs_'
QUIT_FOCUS_CALC_CB = '=qfc'
#
STOP_CONTROLLER = '=sc-'
STOP_RECONSTRUCTOR = '=sr-'
STOP_IMAGE_CAPTURE_BTN = '=sic-'
STOP_SAFEMON_BTN = '+ssm-'
STOP_STITCHER_BTN = '+qSt'
STOP_STAINER_BTN = '+sst'
STOP_FOCUS_CALC_BTN = '+sfc'
STOP_TA_BTN = '+tta'
START_TA_BTN = '+ta'
#
TEST_FOCUS_ON = 'tF'
TEST_FOCUS_OFF = 'tf'
TEST_SCAN_ON = 'tS'
TEST_SCAN_OFF = 'ts'
#
cMOVE_TO_LOAD_POS_K = '*2l'
cMOVE_TO_SCAN_POS_K = '*2s'
cMOVE_TO_SNAP_POS_K = '*2sp'
#
# Temperature frame keys
TEMP_1_TXT = '^t1'
TEMP_1M_TXT = '^M1'
TEMP_1m_TXT = '^m1'
TEMP_1_ICON = '^i1'
#
TEMP_2_TXT = '^t2'
TEMP_2M_TXT = '^M2'
TEMP_2m_TXT = '^m2'
TEMP_2_ICON = '^i2'
#
TEMP_3_TXT = '^t3'
TEMP_3M_TXT = '^M3'
TEMP_3m_TXT = '^m3'
TEMP_3_ICON = '^i3'

TEMP_4_TXT = '^t4'
TEMP_4M_TXT = '^M4'
TEMP_4m_TXT = '^m4'
TEMP_4_ICON = '^i4'
#
TEMP_5_TXT = '^t5'
TEMP_5M_TXT = '^M5'
TEMP_5m_TXT = '^m5'
TEMP_5_ICON = '^i5'
#
TEMP_6_TXT = '^t6'
TEMP_6M_TXT = '^M6'
TEMP_6m_TXT = '^m6'
TEMP_6_ICON = '^i6'
#
TEMP_7_TXT = '^t7'
TEMP_7M_TXT = '^M7'
TEMP_7m_TXT = '^m7'
TEMP_7_ICON = '^i7'
#
# work directories needed by UI
SAVED_PATHS_DIR = "/saved-paths"
REGION_PATHS_DIR = "/REGION_PATHS"
EXPORTED_PATHS_DIR = "/EXPORTED_PATHS"
CAMERA_PATHS_DIR = "/home/gander/Development/ILLUMISONICS/Gander/CAMERA-JSON"
SAVED_CALIBRATION_DIR = "/saved-calibration"
SAVED_CSV_PATH_LOGS_DIR = "/saved-csv-path-logs"

# update events from MessageHandler to main_window
# note some of the constants are coming from implementation_constants.py
cRETURNED_ERROR = '@#$!'
cUPDATE_MOVES_LOG_EVENT = '+uml'
cUPDATE_MOVES_LOG_COMPLETED_EVENT = '+umlC'
cUPDATE_PROGRAMMED_MOVES_LOG_EVENT = '+upml'
cUPDATE_PROGRAMMED_MOVES_XYZ_LOG_EVENT = '+uxyz'
cUPDATE_STATUS_BAR_EVENT = '+usb'
cUPDATE_INFO = '=ui'
cOBJECT_TO_UPDATE_1 = '=otu1'
cUPDATE_VALUE_1 = '=uv1'
cUPDATE_ERROR_MESSAGE = '=uErr'
cFILE_ROTATION_NOTIFICATION = '=fRN'
cDETECTION_WARMUP_START = '=gW'
cDETECTION_STOP = '=gS'
cDETECTION_DONT_STOP = '=gD'
cDETECTION_LASER_STATE_NOTIFICATION = '=gN'
cDETECTION_ON_STATUS_NOTIFICATION = '=gOnSN'

# calibration dictionary
cX = 'X'
cY = 'Y'
cZ = 'Z'
cROW = 'Row'
cCOL = 'Col'
#
cDONOR_COUNT_KEY = 'd'
cBORROWER_COUNT_KEY = 'b'
cTOTAL_COUNT_KEY = 't'
#
#================================================================================================================
# Camera Calibration, position calibration, grid calibration, grid size
# Demo A constants ==============================================================================================
cCAM_CCW_ROT_DEG = 0.7666 #0
cSECTION_HEIGHT_MM = 0.50
cSECTION_WIDTH_MM = 0.20
cSECTION_OVERLAP_MM = 0.02
cSECTION_HEIGHT_TO_OVERLAP_MM = cSECTION_HEIGHT_MM - cSECTION_OVERLAP_MM
cSECTION_WIDTH_TO_OVERLAP_MM = cSECTION_WIDTH_MM - cSECTION_OVERLAP_MM
## SECTION GRID
cMASTER_ROW_COUNT = 535
cMASTER_COL_COUNT = 306
##
##
cSCALE_DOWN_FACTOR = 0.5    # original image is reduced by this factor to create a temp work image
## pixel size of the image
cCAMERA_PER_PIXEL_WIDTH_MM = 0.014230724073320 #0.0143169805710572    # camera pixel width
cCAMERA_PER_PIXEL_HEIGHT_MM = 0.014230724073320 #0.0143169805710572   # camera pixel height
#
cCAMERA_SCALE_HEIGHT_TO_WIDTH = cCAMERA_PER_PIXEL_HEIGHT_MM / cCAMERA_PER_PIXEL_WIDTH_MM

# pixel size conversion between camera mm / pixel and screen mm/pixel
cCAMERA_WIDTH_PIXELS_PER_MM = 1 / cCAMERA_PER_PIXEL_WIDTH_MM
cCAMERA_HEIGHT_PIXELS_PER_MM = 1 / cCAMERA_PER_PIXEL_HEIGHT_MM
cPER_PIXEL_WIDTH_MM = cCAMERA_PER_PIXEL_WIDTH_MM
cPER_PIXEL_HEIGHT_MM = cCAMERA_PER_PIXEL_HEIGHT_MM / cCAMERA_SCALE_HEIGHT_TO_WIDTH
##
cSECTION_HEIGHT_PIXEL_COUNT = cSECTION_HEIGHT_MM / cPER_PIXEL_HEIGHT_MM
cSECTION_HEIGHT_TO_OVERLAP_PIXEL_COUNT = cSECTION_HEIGHT_TO_OVERLAP_MM / cPER_PIXEL_HEIGHT_MM
cSECTION_WIDTH_PIXEL_COUNT = cSECTION_WIDTH_MM / cPER_PIXEL_WIDTH_MM
cSECTION_WIDTH_TO_OVERLAP_PIXEL_COUNT = cSECTION_WIDTH_TO_OVERLAP_MM / cPER_PIXEL_WIDTH_MM
#
cSCALED_SECTION_HEIGHT_MM = cSECTION_HEIGHT_MM * cSCALE_DOWN_FACTOR
cSCALED_SECTION_HEIGHT_TO_OVERLAP_MM = cSECTION_HEIGHT_TO_OVERLAP_MM * cSCALE_DOWN_FACTOR
cSCALED_SECTION_WIDTH_MM = cSECTION_WIDTH_MM * cSCALE_DOWN_FACTOR
cSCALED_SECTION_WIDTH_TO_OVERLAP_MM = cSECTION_WIDTH_TO_OVERLAP_MM * cSCALE_DOWN_FACTOR
#
cSCALED_SECTION_HEIGHT_PIXEL_COUNT = cSECTION_HEIGHT_PIXEL_COUNT * cSCALE_DOWN_FACTOR
cSCALED_SECTION_HEIGHT_TO_OVERLAP_PIXEL_COUNT = cSECTION_HEIGHT_TO_OVERLAP_PIXEL_COUNT * cSCALE_DOWN_FACTOR
cSCALED_SECTION_WIDTH_PIXEL_COUNT = cSECTION_WIDTH_PIXEL_COUNT * cSCALE_DOWN_FACTOR
cSCALED_SECTION_WIDTH_TO_OVERLAP_PIXEL_COUNT = cSECTION_WIDTH_TO_OVERLAP_PIXEL_COUNT * cSCALE_DOWN_FACTOR
#
cGRID_LINE_SCALED_WIDTH_IN_PIXELS = cMASTER_COL_COUNT * cSCALED_SECTION_WIDTH_TO_OVERLAP_PIXEL_COUNT
cGRID_LINE_SCALED_HEIGHT_IN_PIXELS = cMASTER_ROW_COUNT * cSCALED_SECTION_HEIGHT_TO_OVERLAP_PIXEL_COUNT
############################################################################################################
##
##
cGRAPH_ID = '-GRAPH-'
##
cRIGHT_BTN_DOWN_KEY = '+D3+'
cRIGHT_BTN_DOWN_EVENT = cGRAPH_ID + cRIGHT_BTN_DOWN_KEY
cRIGHT_BTN_MOTION_KEY = '+m3+'
cRIGHT_BTN_MOTION_EVENT = cGRAPH_ID + cRIGHT_BTN_MOTION_KEY
cRIGHT_BTN_UP_KEY = '+u3+'
cRIGHT_BTN_UP_EVENT = cGRAPH_ID + cRIGHT_BTN_UP_KEY

cCENTER_DOWN_KEY = '+D2+'
cCENTER_BTN_DOWN_EVENT = cGRAPH_ID + cCENTER_DOWN_KEY
cCENTER_BTN_MOTION_KEY = '+m2+'
cCENTER_BTN_MOTION_EVENT = cGRAPH_ID + cCENTER_BTN_MOTION_KEY
cCENTER_BTN_UP_KEY = '+u2+'
cCENTER_BTN_UP_EVENT = cGRAPH_ID + cCENTER_BTN_UP_KEY

cLEFT_BTN_DOWN_KEY = '+D1+'
cLEFT_BTN_DOWN_EVENT = cGRAPH_ID + cLEFT_BTN_DOWN_KEY
cLEFT_BTN_MOTION_KEY = '+m1+'
cLEFT_BTN_MOTION_EVENT = cGRAPH_ID + cLEFT_BTN_MOTION_KEY
cLEFT_BTN_UP_KEY = '+u1+'
cLEFT_BTN_UP_EVENT = cGRAPH_ID + cLEFT_BTN_UP_KEY

cALL_MOUSE_EVENTS = [cLEFT_BTN_DOWN_EVENT, cLEFT_BTN_MOTION_EVENT, cLEFT_BTN_UP_EVENT,
                     cCENTER_BTN_DOWN_EVENT, cCENTER_BTN_MOTION_EVENT, cCENTER_BTN_UP_EVENT,
                     cRIGHT_BTN_DOWN_EVENT, cRIGHT_BTN_MOTION_EVENT, cCENTER_BTN_UP_EVENT,]
##
cCONTROL_DOWN_LEFT_BINDING = '<Control_L>'
cCONTROL_DOWN_RIGHT_BINDING = '<Control_R>'
cCONTROL_DOWN_KEY = 'CTRL-D'
cCONTROL_UP_LEFT_BINDING = '<KeyRelease-Control_L>'
cCONTROL_UP_RIGHT_BINDING = '<KeyRelease-Control_R>'
cCONTROL_UP_KEY = 'CTRL-U'
#
cSHIFT_DOWN_LEFT_BINDING = '<Shift_L>'
cSHIFT_DOWN_RIGHT_BINDING = '<Shift_R>'
cSHIFT_DOWN_KEY = 'SHIFT-D'
cSHIFT_UP_LEFT_BINDING = '<KeyRelease-Shift_L>'
cSHIFT_UP_RIGHT_BINDING = '<KeyRelease-Shift_R>'
cSHIFT_UP_KEY = 'SHIFT-U'
#
cALT_DOWN_LEFT_BINDING = '<Alt_L>'
cALT_DOWN_RIGHT_BINDING = '<Alt_R>'
cALT_DOWN_KEY = 'ALT-D'
cALT_UP_LEFT_BINDING = '<KeyRelease-Alt_L>'
cALT_UP_RIGHT_BINDING = '<KeyRelease-Alt_R>'
cALT_UP_KEY = 'ALT-U'
#
#
cIMAGE_KEY = 'image'
cCOLUMN_KEY = 'col'
cZOOM_LEVEL_LBL = 'zll'
cROW_COL_UPDATE_KEY = 'rcU'
cSCAN_COMPLETION_KEY = '&sc'
# button keys
cSNAP_LBL = 'Snap'
cSNAP_KEY = 'sn'
cSAVE_LBL = 'Save'
cSAVE_KEY = 's'
cZOOM_IN_LBL = 'Zoom In'
cZOOM_IN_KEY = 'z+'
cZOOM_OUT_LBL = 'Zoom Out'
cZOOM_OUT_KEY = 'z-'
cREMOVE_LBL = 'Remove ALL Selections'
cREMOVE_KEY = 'r'
cSNAP_STATUS_BAR = '@sSB'
cHIDE_SELECTED_SECTIONS_LBL = 'Hide Selections'
cSHOW_SELECTED_SECTIONS_LBL = 'Show Selections'
cHIDE_SELECTIONS_KEY = 'h'
cSELECT_GRID_ANCHOR_LBL = 'Select Anchor Point'
cSELECT_GRID_ANCHOR_KEY = 'b'
cEXPORT_JSON_KEY = '!ejp'
cLOAD_PATH_KEY = 'lpk'
cLOAD_AND_SEND_LUCAS_PATH_KEY = 'lpa'
cLOAD_AND_SEND_PLANE_PATH_KEY = '!ppk'
cSCAN_PATH_LBL = 'Scan'
cSCAN_PATH_KEY = 'scan'
cRESUME_SCAN_LBL = 'Resume'
cRESUME_SCAN_KEY = 'rsk'
cCANCEL_SCAN_PATH_LBL = 'Cancel'
cCANCEL_SCAN_PATH_KEY = 'cSP'
cSLIDE_INFO_BTN = 'sib'
cBORDER_LBL = 'bL'
cDONOR_COUNT_LBL = 'dc'
cBORROWER_COUNT_LBL = 'br'
cTOTAL_COUNT_LBL = 'tot'
cREGION_COUNT_LBL = 'rgc'
cSCAN_SECTION_TXT = 'Scan'
cBORDER_SECTION_TXT = 'Border'
cRECTANGLE_LBL = 'Rectangle'
cRECTANGLE_DELETES_LBL = 'Rectangle Deletes'
cPOLYGON_LBL = 'Polygon'
cSELECTION_TYPE_LBL = 'Selection Type:'
cPOLY_OR_RECT_KEY = 'por'
cZOOM_SLIDER_KEY = 'zs'
cSLIDER_LEFT_UP_BINDING = '-SR-U'
cSLIDER_BUTTON_UP_EVENT = cZOOM_SLIDER_KEY + cSLIDER_LEFT_UP_BINDING
cGRID_CB_LBL = 'Grid'
cGRID_TOGGLE_ON_LBL = 'Grid ON'
cGRID_TOGGLE_OFF_LBL = 'Grid OFF'
cGRID_CB_KEY = 'sg'
cBUTTON_SEL1_COLOR = 'white on green'
cBUTTON_SEL2_COLOR = 'white on red'
cZOOM_VALUE_CHANGE = 0.1
#
cMASTER_GRID_BOX_LINE_WIDTH = 1
cMASTER_GRID_BOX_COLOR = 'red'
cSELECTION_RECTANGLE_LINE_WIDTH = 1
cSELECTION_RECTANGLE_COLOR = 'grey'
cSELECTION_DELETE_RECTANGLE_COLOR = 'red'
cSECTION_FILL_COLOR = 'grey'
cGRID_LINE_WIDTH = 1
cGRID_LINE_COLOR = 'green'
cPOLYGON_LINE_WIDTH = 2
cPOLYGON_LINE_COLOUR = 'blue'
#
# location of a temporary scaled image file
cLINUX_ONLY_MEM_FS = "/dev/shm/"
cTEMP_RAW_FILE_NAME = "tmp_raw.tif"
cTEMP_RAW_ROT_FILE_NAME = "tmp_rot.tif"
cTEMP_FILE_NAME = "tmp.tif"
cTEMP_TAG_FILE_NAME = "tag.tif"
cSLIDE_FILE_NAME = "slide.tif"
cPASTED_IMAGE_FILE_NAME = "pasted.tif"
cSLIDE_INFO_FILE_NAME = "slide_info.json"
cSCAN_PATH_FILE_NAME = "path.json"
cSCAN_TEMP_FILE_NAME = "scan_temp.csv"
cTEMPERATURE_TABLE_KEY = '&tt'
# scan info window info keys
DIR_NAME_IN = '%%'
CASE_IN = '%cii'
CASE_ID_TAG = 'CaseID'
DATE_IN = '%dati'
DATE_TAG = 'Date'
SAMPLE_TYPE_IN = '%sti'
SAMPLE_TYPE_TAG = 'SampleType'
TISSUE_TYPE_IN = '%tti'
TISSUE_TYPE_TAG = 'TissueType'
DESCRIPTION_IN = '%dei'
DESCRIPTION_TAG = 'Description'
SLIDE_LABEL_PATH_TAG = 'TagPath'
PASTED_IMAGE_PATH_TAG = 'PasteImagePath'

RESET_FORM_BTN = '%re-'
SAVE_AND_CONTINUE_BTN = '%sac-'
OPEN_BTN = '%bo'
PASTE_PATH_IMG_BTN = '%ppi-'
CLEAR_PASTED_IMG_BTN = '%cpi-'
TAG_PATH_MSG = '@tpm'
TAG_PATH_PARAM = '@tpp'
TAG_IMG = "%ti-"
PATH_IMG = "%pi-"
#
cRESET_ON_SNAP = '#ros'
# scan window consts
TAG_CROP = (0, 144, 616, 940)
CAM_CROP = (255.0, 800.0, 5350.0, 2576.0)
#
CAM_CCW_ROT_DEG = 0